import type { EntityProfile } from '@crayon-world/shared';

export const MOCK_ENTITIES: EntityProfile[] = [
  {
    name: 'Wolf',
    archetype: 'walking',
    movementStyle: 'prowling',
    habitat: 'land',
    landSpeed: 7,
    agility: 6,
    energy: 5,
    maxHealth: 45,
  },
  {
    name: 'Eagle',
    archetype: 'flying',
    movementStyle: 'swooping',
    habitat: 'air',
    airSpeed: 8,
    landSpeed: 3,
    agility: 6,
    energy: 5,
    maxHealth: 30,
  },
  {
    name: 'Oak',
    archetype: 'rooted',
    movementStyle: 'swaying',
    habitat: 'land',
    landSpeed: 1,
    agility: 1,
    energy: 2,
    maxHealth: 80,
  },
  {
    name: 'Frog',
    archetype: 'walking',
    movementStyle: 'hopping',
    habitat: 'land',
    landSpeed: 5,
    waterSpeed: 4,
    agility: 6,
    energy: 7,
    maxHealth: 20,
  },
  {
    name: 'Cloud',
    archetype: 'drifting',
    movementStyle: 'bobbing',
    habitat: 'air',
    airSpeed: 3,
    agility: 2,
    energy: 3,
    maxHealth: 25,
  },
  {
    name: 'Rock',
    archetype: 'stationary',
    movementStyle: 'still',
    habitat: 'land',
    landSpeed: 1,
    agility: 1,
    energy: 1,
    maxHealth: 100,
  },
  {
    name: 'Fish',
    archetype: 'walking',
    movementStyle: 'scampering',
    habitat: 'water',
    waterSpeed: 7,
    agility: 7,
    energy: 6,
    maxHealth: 15,
  },
  {
    name: 'Crab',
    archetype: 'walking',
    movementStyle: 'scampering',
    habitat: 'water',
    waterSpeed: 4,
    landSpeed: 3,
    agility: 5,
    energy: 5,
    maxHealth: 35,
  },
];
