import type { EntityProfile } from '@crayon-world/shared';

export const MOCK_ENTITIES: EntityProfile[] = [
  {
    name: 'Wolf',
    archetype: 'walking',
    movementStyle: 'prowling',
    speed: 7,
    agility: 6,
    energy: 5,
    maxHealth: 45,
  },
  {
    name: 'Eagle',
    archetype: 'flying',
    movementStyle: 'swooping',
    speed: 8,
    agility: 6,
    energy: 5,
    maxHealth: 30,
  },
  {
    name: 'Oak',
    archetype: 'rooted',
    movementStyle: 'swaying',
    speed: 1,
    agility: 1,
    energy: 2,
    maxHealth: 80,
  },
  {
    name: 'Fire',
    archetype: 'spreading',
    movementStyle: 'creeping',
    speed: 6,
    agility: 3,
    energy: 9,
    maxHealth: 20,
  },
  {
    name: 'Cloud',
    archetype: 'drifting',
    movementStyle: 'bobbing',
    speed: 3,
    agility: 2,
    energy: 3,
    maxHealth: 25,
  },
  {
    name: 'Rock',
    archetype: 'stationary',
    movementStyle: 'still',
    speed: 1,
    agility: 1,
    energy: 1,
    maxHealth: 100,
  },
];
